List blog posts
dthisner/viking-craftsman pull request #2
Opened 2021-04-27 22:03 UTC by dthisner

Adding functionality to list blog posts.

It grabs blog post from Bloggers API and lists them

Added Unit Tests

2021-04-27 22:08 UTC, thm-design commented
Hi hi

2021-04-28 19:36 UTC, thm-design requested changes

2021-04-28 19:36 UTC, thm-design commented on src/api/blogger.js
> +const baseUrl = 'https://www.googleapis.com/blogger/v3/blogs'
Nit: this could also be stored in an env var.

2021-04-28 19:36 UTC, thm-design commented on src/components/App.js
> +        {/* <Footer /> */}
How dare you.

2021-04-28 19:36 UTC, thm-design commented on src/pages/BlogPosts.js
> +  }, [])
There is no error handling here, and no cancellation of the network request in the event this component is un-mounted.
Here is an example with error handling and cancellation: 

`const [apiData, setApiData] = useState(null);

    useEffect(() => {
        const source = axios.CancelToken.source();

        axios.get("https://jsonplaceholder.typicode.com/todos", {
            cancelToken: source.token
        }).then(response => {
            setApiData(response.data);
        }).catch(err => {
            console.log("Catched error: " + e.message);
        });

        return () => {
            source.cancel("Component got unmounted");
        };
    }, []);`

Source: https://since1979.dev/cancel-axios-request-to-prevent-react-from-yelling-at-you

2021-04-28 19:36 UTC, thm-design commented on src/pages/BlogPosts.js
> +      <div>{RenderPagnation(pagnation)}</div>
Nit: So react components are usually named with uppercase camel,` <MyThing />` etc..  While functions are usually small case camel, `myThing()`.

Here you are using the component casing convention and using the function style ('RenderPagnation(pagnation)'), which works, but in the light of consistency and less confusion you could just do this: `<div><RenderPagnation pagnation={pagnation} />}</div>`

But don't forget to add curly brackets around the "prop" if you will use it as a component: `const RenderPagnation = ({ pagnation }) => {` etc.

2021-04-28 19:40 UTC, thm-design commented on src/pages/BlogPosts.js
> +      <div>{RenderPagnation(pagnation)}</div>
PS: I know you already know this above ^

2021-04-28 21:27 UTC, dthisner commented on src/components/App.js
> +        {/* <Footer /> */}
it asked for it! :D

2021-04-29 00:20 UTC, merged